JobCenterNames:
- center1
- center2
JobList:
- job1
- job2
PlayerShopIds:
- id1
- id2
MaxJoinedTowns: 6
MaxPlayershops: 6
localeCountry: DE
ExtendedInteraction: false
MaxRentedDays: 6
homes: false
localeLanguage: de
