package com.ue.exceptions;

public enum JobExceptionMessageEnum {

	JOB_DOES_NOT_EXISTS,
	JOB_ALREADY_EXISTS,
	JOBCENTER_ALREADY_EXISTS,
	JOBCENTER_DOES_NOT_EXIST,
	ENTITY_ALREADY_EXISTS,
	ENTITY_DOES_NOT_EXIST,
	ITEM_ALREADY_EXISTS,
	ITEM_DOES_NOT_EXIST,
	JOB_NOT_EXIST_IN_JOBCENTER,
	LOOTTYPE_ALREADY_EXISTS,
	LOOTTYPE_DOES_NOT_EXIST,
	JOB_ALREADY_EXIST_IN_JOBCENTER,
	CANNOT_LOAD_JOB,
	CANNOT_LOAD_JOBCENTER
}
