package com.ue.exceptions;

public enum ShopExceptionMessageEnum {

	SHOP_CHANGEOWNER_ERROR,
	SHOP_DOES_NOT_EXIST,
	SHOP_ALREADY_EXISTS,
	INVALID_CHAR_IN_SHOP_NAME,
	INVALID_PRICES,
	INVENTORY_SLOT_EMPTY,
	ITEM_ALREADY_EXISTS,
	ITEM_DOES_NOT_EXIST,
	ITEM_CANNOT_BE_DELETED,
	ITEM_UNAVAILABLE,
	ERROR_ON_RENAMING,
	ALREADY_RENTED,
	RESIZING_FAILED,
	CANNOT_LOAD_SHOPITEM,
	CANNOT_LOAD_SHOP
	
}
